### PR TITLE
Add support suffix for private images.

### PR DESCRIPTION
**Pull request by RTLcoil**

### CODE REVIEW

**Comment by RTLcoil** [comment]
@ronen-burin please check

**Comment by ronen-burin** [comment]
Tests are failing. please run the tests and make sure they are green.

**Comment by RTLcoil** [comment]
@ronen-burin The branch is our, but the tests are not and we missed it. It's a minor problem with a few tests in a public branch and we'll fix it.
In any case, please provide me with credentials to reconfigure Travis because since we last set it up things changed and now it requires a different setup to operate properly.

**Comment by RTLcoil** [comment]
@ronen-burin there's an old test, which was written a while ago

 [Test]
        public void TestAutoTaggingRequest()
        {
            //should support requesting auto tagging

            var res = m_cloudinary.Upload(new ImageUploadParams()
            {
                File = new FileDescription(m_testImagePath),
                AutoTagging = 0.5f
            });

            Assert.AreEqual(HttpStatusCode.BadRequest, res.StatusCode);
            Assert.True(res.Error.Message.StartsWith("Must use"));
        }

It was always working but now it doesn't. Did anything change on the server? How should this test work in this case?

**Comment by tocker** [comment]
auto_tagging no longer results in error when categorisation is missing. You can delete that test.

**Pull request merged**
