### PR TITLE
Added pages to GetResourceParams.cs

### PR DESCRIPTION
**Pull request by aibars**
Added the ability to get pages of multi-pages

### CODE REVIEW

**Comment by const-cloudinary** [comment]
@aibars , thank you for contribution!
I would be grateful if you could write a unit test for this parameter.

We already have similar tests, like `TestGetResourceWithMetadata`
We also have a `m_testPdfPath` PDF file in unit test resources that can be used for this purpose.

**Comment by aibars** [comment]
@const-cloudinary Sure! I'll do that after I get some free time. In the meantime, could you give me an example of what should I add to the `ApiBaseAddress` in the appsettings.json file? Thank you

**Comment by aibars** [comment]
@const-cloudinary cool, I've added a test and it is passing!

**Comment by const-cloudinary** [comment]
@aibars,  thank you!

**Comment by aibars** [comment]
@const-cloudinary do you know when will the Nuget package get updated?

**Comment by const-cloudinary** [comment]
@aibars, just released it

**Comment by aibars** [comment]
Thank you!

**Pull request merged**
