### PR TITLE
Cloudinary netcore

### PR DESCRIPTION
**Pull request by RTLcoil**

### CODE REVIEW

**Comment by joelharkes** [comment]
Sad cloudinary doesnt take the time to accept your pull requests and not even respond on it. I Made a new verison which has a a bit less impact but is ready for core.

**Comment by tocker** [comment]
@joelharkes Thank you for submitting your PR and for commenting here!
We are working @RTLcoil on this PR and hope to release it soon. As this is a major change it takes longer to ensure we provide a library that is compatible with various customer code configurations.

**Comment by RTLcoil** [comment]
@joelharkes thanks for your support and I have good news for you - we've completed the netcore and it should be published soon!

**Comment by joelharkes** [comment]
thanks for reporting back, we cant wait to see what took almost a year to build.

A few questions from the community?
* Will it be open source or will you just publish a generated version on github?
* Btw do you have/ will there be a swagger api or yaml file about your api?
* How wil you deal with further contributions from the community?
* If you'd like the community to participate, what area's would you like it to help out?

If its easy enough to port from old to new, i might close my nuget packages after we ported.

**Pull request closed without merging**
