### PR TITLE
Update TAGPARAM.cs

### PR DESCRIPTION
**Pull request by Azziet**
adding resource type to tagparam class

### CODE REVIEW

**Comment by ronen-burin** [comment]
please add test that cover this parameter

**Comment by RTLcoil** [comment]
@ronen-burin this parameter is covered by so many tests and is using other tests with tags, that covering it separately with another test may not be necessary.
https://github.com/cloudinary/CloudinaryDotNet/blob/master/Cloudinary.Test/CloudinaryTest.cs#L851

Let me know if you want me to still proceed with a separate test for it.

**Comment by ronen-burin** [comment]
If it's covered, no need.

**Comment by RTLcoil** [comment]
Cool, returning the request back to you then.

**Pull request closed without merging**
